### ISSUE TITLE
Improved caching for offline operation

### ISSUE THREAD

**Issue by N-Coder** [N-Coder/studip-fuse#1]
All of the following is required to allow offline operation

# Cache Management
- [x] allow custom cache validation
  - cached results containing/wrapping a failed future shouldn't be kept in cache
- [x] failed Downloads should be dropped from cache
- [x] when restarting a failed Download, its previously successfully downloaded parts should be kept/reused and only the failed parts/chunks retried
- [x] add ttl-based cache clearing
- [ ] make cache persistable / serializeable
- [x] use factory for StudIP API data model classes based on object UIDs, preventing duplicate objects
- [x] directly cache the results of the StudIP API Session getter functions
- [x] only persist the now unique instances of the StudIP API data model classes
- [x] reuse expired cache-value as fallback when new attempt fails too often or takes to long
- [x] implement circuit-breaker algorithm for checking for network connectivity and deciding whether (or how often) a function should be retried or the expired value should be reused

# Task Management
- [ ] not being able to login in when starting loop will always prevent startup when offline
- [ ] session termination during runtime is not handled
- [x] store cached values on disk periodically and load then on program start
- [ ] allow eager loading of certain directories (with lower priority than user/FUSE operations)
- [ ] implement framework for lifecycle tasks
  1. startup tasks (e.g. restore model),
  2. low priority background tasks (e.g. reset semester selection, save model),
  3. required/dependency (cached) tasks (e.g. login) and
  4. shutdown tasks (e.g. reset semester selection, save model)

# Future Work
- [x] cached functions and download parts should be retried immediately on temporary network failures 
- [x] use ephemeral caching on all other functions (if really needed)
- [ ] test fuse functionality, cache logic and API functions
- [ ] allow user to switch between online and offline operation
  - provide two hidden directories that also contain the full directory tree, but using only cached values (`/.cached/*`) / only online values (`/.online/*`)
  - or make appindicator allowing to show and switch modes
- [ ] make all caching and circuit-breaker related values (timeouts, thresholds,...) configurable
- [ ] properly implement and tune HTTP timeout and status code handling

**Comment by N-Coder** [comment]
Session management is also not ready for offline operation:
- [ ] not being able to login in when starting loop will always prevent startup
- [ ] session termination during runtime is not handled

**Comment by N-Coder** [comment]
Blindly caching everything mit not be efficient enough, so for being able to persist cached values we need to
- [x] use factory for StudIP API data model classes based on object UIDs, preventing duplicate objects
- [ ] directly cache the results of the StudIP API Session getter functions
- [ ] only persist the now unqiue instances of the StudIP API data model classes
- [ ] use ephemeral caching on all other functions (if really needed)
- [ ] this should also allow simple Mocking of the API leading to better testability

**Comment by N-Coder** [comment]
Restructured issue description, initial description was

> - [x] allow custom cache validation
>   - cached results containing/wrapping a failed future shouldn't be kept in cache
> - [x] failed Downloads should be dropped from cache
> - [x] when restarting a failed Download, its previously successfully downloaded parts should be kept/reused and only the failed parts/chunks retried
> - [x] add ttl-based cache clearing
> - [ ] cached functions should be retried on temporary network failures 
> - [ ] reuse expired cache-value as fallback when new attempt fails too often or takes to long
>   - this requires an algorithm for checking for network connectivity and deciding whether (or how often) a function should be retried or the expired value should be reused
>   - should provide two hidden directories that also contain the full directory tree, but using only cached values (`/.cached/*`) / only online values (`/.online/*`)
> - [ ] allow eager loading of certain directories (with lower priority than user/FUSE operations)
> - [x] also store cached values on disk and load then on program start
> - [ ] all the above should allow offline operation
> 
> Session management is also not ready for offline operation:
> - [ ] not being able to login in when starting loop will always prevent startup
> - [ ] session termination during runtime is not handled
> 
> Blindly caching everything mit not be efficient enough, so for being able to persist cached values we need to
> - [x] use factory for StudIP API data model classes based on object UIDs, preventing duplicate objects
> - [x] directly cache the results of the StudIP API Session getter functions
> - [x] only persist the now unqiue instances of the StudIP API data model classes
> - [ ] use ephemeral caching on all other functions (if really needed)
> - [ ] this should also allow simple Mocking of the API leading to better testability

**Comment by N-Coder** [comment]
## Awesome List

with generic tools to solve various of our problems here

### Model Data / Schema Instance Repository
- [Blog Article](https://ict.swisscom.ch/2017/12/python-schema/)
- [attrs](http://www.attrs.org/en/stable/) / [cattrs](https://github.com/Tinche/cattrs)
- [marshmallow](https://marshmallow.readthedocs.io/en/latest/why.html#why)
- [Scrapy HTML Data Scraping Tool](https://scrapy.org/)

### Model Data / Ephemeral Data Caching
- [async_lru](https://github.com/aio-libs/async_lru)
- [aiocache](https://github.com/argaen/aiocache)
- [shared / cached tasks in trio](https://github.com/python-trio/trio/issues/266) \(TODO comment)

### HTTP Caching
- [cachecontrol](https://github.com/ionrock/cachecontrol)
- [httpcache](https://github.com/Lukasa/httpcache)
- [requests-cache](https://github.com/reclosedev/requests-cache)

### (HTTP) Retrying
- [Blog Article](http://allyouneedisbackend.com/blog/2017/09/15/how-backend-software-should-retry-on-failures/)
	- [riprova](https://github.com/h2non/riprova) ([aiohttp example](https://github.com/h2non/riprova/blob/master/examples/http_asyncio.py))
	- [backoff](https://github.com/litl/backoff)
	- [tenacity](https://github.com/jd/tenacity)
	- [retrying](https://github.com/rholder/retrying)
- [aiohttp sample code](https://github.com/aio-libs/aiohttp/issues/850)
- [urllib3 util.retry.Retry](http://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.retry.Retry) (also used by [requests](https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request))

### Downloads

- [requests-toolbelt stream download utils](https://toolbelt.readthedocs.io/en/latest/downloadutils.html)

### Other Event Loops

[On Threads...](https://glyph.twistedmatrix.com/2014/02/unyielding.html)

- Candidates
	- [Eventlet](http://eventlet.net/)
	- [gevent](http://www.gevent.org/) + [greenlet](https://greenlet.readthedocs.io/en/latest/) + [libev](http://software.schmorp.de/pkg/libev.html) or [libuv](http://docs.libuv.org/en/v1.x/)
	- Twisted
	- Tornado
	- Asyncio
	- [Curio](https://github.com/dabeaz/curio#important-disclaimer)
	- [Trio](https://trio.readthedocs.io/en/latest/) ([Examples / Cookbook / Patterns](https://github.com/python-trio/trio/issues/472))
- Comparisions
	- [Gevent vs Eventlet](https://blog.gevent.org/2010/02/27/why-gevent/)
	- [Twisted / Tornado / Other Async Web Frameworks](http://dhilipsiva.com/2013/05/19/python-libraries-django-twisted-tornado-flask-cyclone-and-pyramid.html)
	- [On Event Loops](https://github.com/AndreLouisCaron/a-tale-of-event-loops)
	- [Python asyncio library diversity](https://quentin.pradet.me/blog/what-color-is-your-python-async-library.html)
	- [Curio compared to Asyncio](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/)
	- [Trio compared to Tornado/Twisted/asyncio/Curio](https://github.com/python-trio/trio/issues/259)
	- [Curio and Trio Thoughts](https://forum.dabeaz.com/t/curio-and-trio-thoughts/173)
	- [Trio-Asyncio interoperability](https://github.com/python-trio/trio/issues/171)
	- [Multio - Curio and Trio abstraction layer](https://github.com/theelous3/multio)
- HTTP Functionality
	- [Twisted + Web Client](https://twistedmatrix.com/documents/14.0.1/web/howto/client.html) or Twisted + Requests [1](https://github.com/requests/requests-threads) and [2](https://pypi.org/project/txrequests/)
	- [Tornado Web Client](http://www.tornadoweb.org/en/stable/httpclient.html)
	- [asks](https://asks.readthedocs.io/en/latest/) - HTTP for Curio and Trio
	- [unified HTTP lib](https://github.com/oliland/async_http_experiments)
	- [urllib3 generic async and h11 support](https://github.com/urllib3/urllib3/issues/1323) ([PR](https://github.com/urllib3/urllib3/pull/1335))
	- [requests 3](https://github.com/requests/requests/labels/3.0) ([old PR](https://github.com/requests/requests/pull/3864))
- old info on asyncio
	- [aiohttp vs. sync requests](http://mahugh.com/2017/05/23/http-requests-asyncio-aiohttp-vs-requests/)
	- [Asyncio Coroutine Patterns: Beyond await](https://medium.com/python-pandemonium/asyncio-coroutine-patterns-beyond-await-a6121486656f)

### Utils
https://pythonhosted.org/aiotk/api.html
https://github.com/vodik/asyncitertools
https://github.com/asyncdef/aitertools/
http://paco.readthedocs.io/en/latest/index.html
https://github.com/python-trio/async_generator
