### ISSUE TITLE
Low-level fuse driver improvements

### ISSUE THREAD

**Issue by N-Coder** [N-Coder/studip-fuse#4]
Currently, there seem to be 3 different fuse libraries for python:
- [fusepy](https://github.com/fusepy/fusepy) (that's what studip-fuse currently uses)
- [python-fuse](https://github.com/libfuse/python-fuse) (official driver by libfuse, but currently unmaintained)
- [python-llfuse](https://github.com/python-llfuse/python-llfuse) (additional driver by fuse maintainer)
    - only provides [low-level API](https://www.usenix.org/system/files/conference/fast17/fast17-vangoor.pdf#page=4), [without inode-path mapping](https://marc.info/?l=fuse-devel&m=139144163617009&w=2)
    - e.g. used by [borg-backup](https://github.com/borgbackup/borg/blob/master/src/borg/fuse.py)
- [pyfuse](https://github.com/nrclark/pyfuse) (new project)

> **Note:**
> [GVfs](https://wiki.gnome.org/Projects/gvfs), the GNOME virtual file system, also provides similar features to FUSE and exposes a lot more details about files and internal FS processes.
> It also exposes the mounted virtual file systems to normal POSIX-applications via FUSE.
> Using GObject-bindings, a backend could be programmed in python.
> Unfortunately, it is by far [not as open for extension](https://wiki.gnome.org/Projects/gvfs/doc#Writing_your_own_backend) as FUSE and also depends on a lot of GNOME-specific libraries.

**TODO**
- [x] Check which of the libraries would be suited best in this use-case.
- [x] Also, include the python low-level (e.g. SEGFAULT) [faulthandler](https://docs.python.org/3/library/faulthandler.html) to log problems with the drivers which are outside of python's reach to stderr or the logfile.
- [x] Also check windows-compatibility (e.g. per this [fusepy PR](https://github.com/fusepy/fusepy/pull/54) via [WinFsp](https://github.com/billziss-gh/winfsp) or this [issue](https://github.com/fusepy/fusepy/issues/57) via [Dokan](https://github.com/dokan-dev/dokany))

**Comment by N-Coder** [comment]
faulthandler was implemented in f3a5c9c and further error handling in 2a0c81d, which was also merged back into fusepy mainline in [PR 103](https://github.com/fusepy/fusepy/pull/103).
WinFsp has also been merged into fusepy in [PR 107](https://github.com/fusepy/fusepy/pull/107) and commits c1eba20 and 1322afe (fixing [damaged file contents on read](https://github.com/billziss-gh/fusepy/issues/8)) enable windows support in StudIP-FUSE.
With everything merged into fusepy mainline, that library is probably the best way to go.

**Comment by N-Coder** [comment]
Following the discussion in https://github.com/fusepy/fusepy/issues/134, there seem to be a lot of further implementations:
- [rianhunter/fusepyng](https://github.com/rianhunter/fusepyng) (fork of fusepy with some issues resolved)
- [pleiszenburg (s-m-e)/refuse](https://github.com/pleiszenburg/refuse) (fork of fusepy, trying to continue development)
- [libfuse/pyfuse3](https://github.com/libfuse/pyfuse3) (another official driver by libfuse, focussed on libfuse3 and asyncio/trio)
- [paulo-raca/fusetree](https://github.com/paulo-raca/fusetree) (high-level object-oriented asyncio API built on low-level pyfuse)
